### ISSUE TITLE
Error while navigating through the tree

### ISSUE THREAD

**Issue by 2gn** [nixlang-wiki/nixlang-wiki#5]
After jumping to [NixOS Quick Start](https://nixlang.wiki/nixos/Quick_Start) page (which is empty at this moment), when clicked on the `nixos` label in the tree (see the image below), it navigates to this url https://nixlang.wiki/en/nixos , which doesn't seem to exist.
<img width="621" alt="image" src="https://github.com/nixlang-wiki/nixlang-wiki/assets/101851090/295df6cf-3893-4938-bc9b-5e752ae5f992">

Thank you for this great project by the way. I've been thinking that I need something like this to Nix community.

**Comment by cafkafk** [comment]
Turns out all sections have a main page, I've fixed this for nix, nixos, and I'll fix it for the other categories asap.

Thanks for the bug report and kind words :heart:
