### ISSUE TITLE
Website on GitHub pages?

### ISSUE THREAD

**Issue by LennyLizowzskiy** [nixlang-wiki/nixlang-wiki#6]
Why hosting a website with static pages on a different platform when you have this repo? You can assign your own domain to it

**Comment by cafkafk** [comment]
> Why hosting a website with static pages on a different platform when you have this repo? You can assign your own domain to it

Well, it isn't just a static page, that's why, else we'd just have used github pages. While the actual pages themself might potentially be served statically, the editing functionality definitely could not.

**Comment by LennyLizowzskiy** [comment]
> > Why hosting a website with static pages on a different platform when you have this repo? You can assign your own domain to it
> 
> Well, it isn't just a static page, that's why, else we'd just have used github pages. While the actual pages themself might potentially be served statically, the editing functionality definitely could not.

Editing via GitHub's Markdown editor and PR-ing them into this repo?

**Comment by cafkafk** [comment]
> > > Why hosting a website with static pages on a different platform when you have this repo? You can assign your own domain to it
> > 
> > 
> > Well, it isn't just a static page, that's why, else we'd just have used github pages. While the actual pages themself might potentially be served statically, the editing functionality definitely could not.
> 
> Editing via GitHub's Markdown editor and PR-ing them into this repo?

I mean yes this could exist, something similar was done in the history of wikis, and we also support doing this as well, but the web editor is a lot neater. Github is a platform for developers, but we want contributions from users as well.
